use_default_settings:
  engines:
    keep_only:
      - brave
      - duckduckgo
      - startpage
      - wikipedia
server:
  limiter: false
  public_instance: false
  image_proxy: false
search:
  formats:
    - html
    - json
outgoing:
  request_timeout: 5.0
engines:
  - name: brave
    disabled: false
  - name: duckduckgo
    disabled: false
  - name: startpage
    disabled: false
  - name: wikipedia
    disabled: false
